---@meta
---
--- @alias nvl.test.assert_fun fun(...:any):any
---
--- @class nvl.test.assert_assertions
--- @field equal nvl.test.assert_fun
--- @field string nvl.test.assert_fun
--- @field same nvl.test.assert_fun

--- @alias nvl.assert_op nvl.test.assert_modifier|nvl.test.assert_assertions

--- @class nvl.test.assert_modifier
--- @field is nvl.assert_op
--- @field are nvl.assert_op
--- @field called_with nvl.assert_op
--- @field was nvl.assert_op
--- @field has nvl.assert_op
--- @field does nvl.assert_op
--- @field not nvl.assert_op
--- @field no nvl.assert_op
--- @field same nvl.assert_op
--- @field equal nvl.assert_op
--- @field spy nvl.assert_op
--- @field stub nvl.assert_op
--- @field is_callable nvl.assert_op
--- @field False nvl.assert_op
--- @field True nvl.assert_op
--- @field Number nvl.assert_op
--- @field Nil nvl.assert_op
--- @field Function nvl.assert_op
--- @field Boolean nvl.assert_op
--- @field String nvl.assert_op
--- @field one_of nvl.assert_op
--- @field has_no_error nvl.assert_op
--- @field has_error nvl.assert_op
--- @field match_path nvl.assert_op
--- @field AllTrue nvl.assert_op
--- @field Table nvl.assert_op

--- @alias nvl.test.luassert nvl.test.assert_modifier
