name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]
        lua-version: ["5.4"]
        luarocks-version: ["3.11.1"]
        include:
          - os: ubuntu-22.04
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Install Lua
        uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Prepare cache
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-deps

      - name: Unit test
        run: |
          mkdir .tmp
          make test
          make coverage
