name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        rev: [nightly, v0.9.5, v0.10.0]
        include:
          - os: ubuntu-22.04
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep
          - os: macos-12
            install-rg: brew update && brew install ripgrep
          - os: windows-2022
            install-rg: choco install ripgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Setup Lua
        uses: leafo/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Prepare cache
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-deps

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Unit test
        run: |
          make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
