name: test

on:
  push:
    branches: master
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  ##############################################################################
  ShellLint:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@master

    - name: Prep
      run: |
        sudo apt-get install -y shellcheck

    - name: Shellcheck
      run: |
        shellcheck ./configure

  ##############################################################################
  TestMatrix:
    strategy:
      matrix:
        lua-version: ["5.4", "luajit"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.lua-version }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: 'Setup macOS deps'
      if: ${{ contains(matrix.os, 'macos') }}
      run: brew install openssl

    - name: Prep
      run: |
        luarocks install busted
        luarocks install cluacov
        luarocks install busted-htest

    - name: Unit Test
      run: |
        make test_lua
    
    
