name: test

on:
  push:
    branches: master
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
 
  ##############################################################################
  TestMatrix:
    strategy:
      matrix:
        lua-version: ["5.4", "luajit"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:

    
    - uses: actions/checkout@master
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.rev }}

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.lua-version }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    
    - name: Prep
      run: |
        luarocks install busted
        luarocks install cluacov
        luarocks install busted-htest

    - name: Unit Test
      run: |
        make test_lua
    
    
